import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextSessionProvider from "@/components/Providers/NextSessionProvider";
import TanstackProvider from "@/components/Providers/TanstackProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-[#0f172a]  to-[#334155]`}
      >
        <NextSessionProvider>
          <TanstackProvider>
            {children}

            <Toaster />
          </TanstackProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}
